### ISSUE TITLE
Include a LICENSE file

### ISSUE THREAD

**Issue by joankaradimov** [yanlinlin82/libffc#2]
I could not find information on the license under which this code is released.

**Comment by yanlinlin82** [comment]
Thank you for your interest in this project. This is a too old project, which I migrated from Google Code years ago. That is why I did not assign any license on it. I do not want to restrict it too much. Therefore, I guess MIT may be a choice if I should name one license. Do you have any suggestion, please?

**Comment by joankaradimov** [comment]
Thanks for the quick reply, even though it's a project that has not been developed for a while!

> I do not want to restrict it too much.

This legally has the opposite effect. When no explicit license is provided, then implicitly everything is copyrighted. This article explains it in more detail: https://choosealicense.com/no-permission/

> Therefore, I guess MIT may be a choice if I should name one license.

MIT sound great!

**Comment by yanlinlin82** [comment]
Thanks very much for your great suggestion. I have added the MIT license file to this project.
